//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_tipo_usuario
    {
        public int idusuario { get; set; }
        public int idtipo_usuario { get; set; }
        public string funcion { get; set; }
    
        public virtual tipo_usuario tipo_usuario { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
