//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario_tramite
    {
        public int id_usuario { get; set; }
        public int id_tramite { get; set; }
        public System.DateTime fecha_modificado { get; set; }
    
        public virtual tramite tramite { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
